apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '100'
    run.googleapis.com/urls: '["https://crm-backend-1027797737108.us-central1.run.app","https://crm-backend-7bx7xdmoeq-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: crm-backend
  namespace: '1027797737108'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 557.0.0
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/sessionAffinity: 'false'
        run.googleapis.com/vpc-access-connector: projects/zazmic-crm/locations/us-central1/connectors/crm-vpc-con
        run.googleapis.com/vpc-access-egress: private-ranges-only
      labels:
        client.knative.dev/nonce: rtyrlmxrqn
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: crm-db-url-production
        image: us-central1-docker.pkg.dev/zazmic-crm/crm-repo/crm-backend:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: crm-cloudrun-sa@zazmic-crm.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
